### PR TITLE
validateVatSum method falsly returns false for spanish VAT number

### LINKED ISSUE #41: validateVatSum method falsly returns false for spanish VAT number
Vat number ESX5910266W is valide according to the VIES service. But the validateVatSum method returns false.

### PR DESCRIPTION
**Pull request by krzaczek**
This should fix all issues with ES Vat numbers

fixes #41

### CODE REVIEW

**Comment by krzaczek** [comment]
@DragonBe I have added missing validation "physical person" VAT number. All tests are green :)

**Comment by hvanoch** [comment]
Hi @krzaczek, I am curious, where did you find the documentation about these "rules"?

**Comment by krzaczek** [comment]
@hvanoch There is an official document but it's not easy to find :)

http://85.81.229.78/systems/DKVIES/-%20Arkiv/Algoritme%E6ndringer/VIES-VAT%20Validation%20Routines-v15.0.doc

**Comment by hvanoch** [comment]
Thank you all.

**Pull request merged**
