### PR TITLE
Improve PHP7.1 features

### PR DESCRIPTION
**Pull request by nyamsprod**
- all methods are now typehinted and with a return type where needed
- validator are simplified
- strict mode is added by default on all classes
- improved default autoloader (without using composer)
- removed deprecated PHPUnit tap report format

### CODE REVIEW

**Comment by nyamsprod** [comment]
@DragonBe This PR does not deal with the `DateTime` it only improved the codebase move to PHP7.1

### Updated/Fixed for the `Vies`  class:

- `Vies::valdateVatSum` is in the Public API but it was not checking if the submitted country code was correct or not So I've added the check and now the method throws an `ViesException` just like all the other methods in the public API which accepts the country code.

- I've added a protected constant `VIES_EU_CONTRY_LIST` to remove class "guessing" in `Vies::validateVatSum` and to keep in sync validator and country listing when using ` Vies::listEuropeanCountries`.  
I don't know if `Vies::VIES_EU_COUNTRY_TOTAL` is still useful but since it is in public API I did not touch it.

- I've switched from `array_key_exists` to `isset` to improve performance.

- `Vies::setHeartBeat` was not returning the Vies object like all the other setter method this is also fixed.

When a ViesServiceException is thrown you can now use ViesServiceException::getPrevious to access the SoapFault exception thrown.

### Updated/Fixed for the `HeartBeat`  class:

- The prive `isConnect` method is removed as it is redundant with the `isAlive` method which is in the public API.

### Updated/Fixed for the VAT Number validator  classes:

All Validator classes are now typehinted with return type. The internals where updated to conform with the expected return type. Sometime a string was return when the method expected to get an integer.

### Tests

- PHPUnit test suite was adapted to validated each country VAT Number and to better spot issue and bug if any where to arise.

- I've also updated PHPUnit configuration to allow the tests to continue even on failure so that I can quickly patch all the error instead of patching one error on each run.

**Comment by DragonBe** [comment]
Hey @nyamsprod, I'm so sorry I've neglected your hard work for so long. Work has taken up most of my free time and I had no time to follow up on this. I'm a terrible maintainer. Please accept my apologies.

What I wanted to ask you is to check why your changes are conflicting with the CZ validations. Having multiple issues with Czech VAT validation indicates to me that I need to re-think about how to process them less fragile. If you have the time, please have a look at the issues and if you can remove the conflicts, that would be super. If not, ping me and I'll have a look at it in two weeks.

I reviewed your changes here and I like what I see. Your changes opens up the possibility to create a VIES MiddleWare component as well, so I would really love to integrate it.

**Comment by nyamsprod** [comment]
@DragonBe hi ... it's been a while I had completely forgotten about this PR ...let me have a look around it this week I'll get back to you ASAP

**Comment by nyamsprod** [comment]
@DragonBe I think I understand the conflicts but I don't know how to solve them. 

- The current `ValidatorTest.php` was very difficult to work with because of the way the dataProvider was set up. I was getting errors but I did not know which validator was yielding the error. So I've modified the dataProvider to be more readable.

- The ValidatorCZ.php suffers the same issue. Difficult to improve without changing some of the internal code. which yield the conflict.

**Comment by krzaczek** [comment]
@nyamsprod maybe I can help with this .. since I rewritten the ValidatorCz lately ... I'll take a look at the conflicts later today.

**Comment by DragonBe** [comment]
@nyamsprod & @krzaczek I will have some time this weekend to look into the issue. If this data provider is causing issues, maybe the approach is not recommended.

@krzaczek if you can't solve it yourself before this weekend, just let me know which roadblocks you hit, as you have more in-depth knowledge of the CZ validation portion.

Thanks again @nyamsprod and @krzaczek for your efforts making this an awesome project. Without your efforts this tool would not have as much value as it currently has. Thank you so much!

**Comment by nyamsprod** [comment]
@krzaczek I've already added your fix on my branch they were missing 👍 I'm updating the validatorTest right now to make it easy to add validator tests.

**Comment by krzaczek** [comment]
@nyamsprod 👍

**Comment by nyamsprod** [comment]
@DragonBe @krzaczek I've split the validatorTest into smaller tests and removed ValidatorTest from my branch to ease test suite maintenance bug it seems that Github does not like it ...

**Comment by DragonBe** [comment]
Let me see if I can figure out what's up with that… Just got a extra 30 minutes for it 😺

**Comment by DragonBe** [comment]
OK, I'm a bit puzzled now… I just pushed merge conflict resolutions to [bakame-php/vies](https://github.com/bakame-php/vies), but now I end-up with Travis failures that are not occurring on my local CI system. To me, this is a horror story as systems should react the same way if all settings are equal. So, looks like Freddy has created a nightmare in my CI Street. Time to go bust some ghosts.

**Comment by DragonBe** [comment]
Looks we need to update the PHPUnit (and other) packages

```
./vendor/bin/phpunit --version
PHPUnit 6.2.2 by Sebastian Bergmann and contributors.
```

Travis uses `PHPUnit 6.4.3 by Sebastian Bergmann and contributors.` Which is weird as it should use the version defined in our `composer.json` file. Feature of Travis-CI or a bug? Doesn't matter, we need to upgrade anyways.

**Comment by DragonBe** [comment]
Updated PHPUnit and I too get the issues reported by Travis-CI… should be fixed in a jiffy 🚀

**Comment by DragonBe** [comment]
All tests passed on Travis and own CI, conflicts resolved and ready to move ahead. I'm going to merge this pull request and release new version!

**Comment by DragonBe** [comment]
Release 2.0.3 is now available!!!

**Pull request merged**
