### PR TITLE
Feature/requester

### PR DESCRIPTION
**Pull request by krzaczek**
Hi last feature .

VIES api allows setting the requester VAT number. If it's set the api returns request identifier. This is actually the only proof that You made a valid check. 

```
If you put your own VAT identification number in the box requester's VAT identification number, the reply will contain a unique consultation number.
If you want to be able to prove to a tax administration of a Member State that you have checked a given VAT number at a given time, and obtained a given validation reply, please keep this consultation number in your archives.
```

The validateVat method has two new parameters which are optional 
```php
public function validateVat($countryCode, $vatNumber, $requesterCountryCode = null, $requesterVatNumber = null)
```

I was thinking of adding a seperate method like setRequester($countryCode, $vatNumber) and then check in validateVAT if the data was set or not ... but decided to just add optional paramaters to validateVat method.

Then You can obtain the identifier by
```php
$response->getIdentifier()
```

If You do not set requester VAT, the identifier is empty.

### CODE REVIEW

**Comment by krzaczek** [comment]
ehhh composer :)

**Comment by DragonBe** [comment]
Hey @krzaczek, I first updated the composer libraries, added the `.lock` file with the project and removed deprecated strict checking from `phpunit.xml`.

Integrated your PR just now, tests still succeed so all is fine.

I need to see why codeclimate and sensiolabs reports a decrease in code coverage, but that's of a lesser importance.

**Comment by DragonBe** [comment]
@krzaczek Now travis validator succeeded as well, all is good.

Can you check the [SensioLabsInsights report #27](https://insight.sensiolabs.com/projects/21b019ce-dd1d-4d16-8b74-880b9ee5e795/analyses/27) though, as there are a few remarks on improving the code. If we could fix those, we're again on top of the QA game as well.

**Comment by krzaczek** [comment]
@DragonBe - PHP classes should be short - this will be fixed by #11

**Pull request merged**
