### PR TITLE
Efforts to make the project welcoming for others

### PR DESCRIPTION
**Pull request by DragonBe**
I enjoy working on the project and love that it's useful to others as well. I
also acknowledge that the project has bugs or not implemented features. To
make the project more accessible, I would like to start an effort to make the
project more welcoming to other contributors of bugs or fixes.

@krzaczek, @jkuchar, @jamesblackwell, @miclf and @spdionis I'd love your
honest feedback on this since you were first contributors to the project and
I value your opinion. Making the project more welcoming I hope that it will
become easier for users to report bugs and for individuals like yourself to
fix these bugs and create a better validator for European VAT ID's.

### CODE REVIEW

**Comment by krzaczek** [comment]
@DragonBe looking good. The CONTRIBUTING.md is very detailed which is nice.

**Comment by DragonBe** [comment]
@krzaczek thank you… so you agree I add this to the project?

**Comment by krzaczek** [comment]
Yes, clear rules are always helpful


pawel (at) mobile

**Comment by DragonBe** [comment]
Thank you @krzaczek, I've integrated it into the project and will push this to branch 1.0 and 2.0

**Comment by miclf** [comment]
Hi @DragonBe & all,

Well, as far as I remember, my only contribution to this repo was just an improvement to the `README`, so I’m not sure I really have a say in this matter.

That said, I agree with @krzaczek on the contributing guide, I think it’s always helpful to have this kind of thing.

Two things, maybe:

1. What you wrote in this document assumes that potential contributors already have some knowledge of the Git command line as well as a few other things. I guess it’s safe for many people but, depending on how much you would like to make contributing welcome, you might want to simplify contributing requirements in order to lower the “threshold”;
2. In `CONTRIBUTING.md`, section 2, there is a link labelled “fork VIES” that points to the GitHub documentation on how to fork a repo. That may be confusing as some may genuinely think, from the label, that this link will allow to automatically fork the VIES repository. You might want to replace that by something less ambiguous, like this:
```
[…] then fork VIES
([see GitHub documentation if you need help](https://help.github.com/articles/fork-a-repo))
and create a branch […]
```

My 0,02 € :)

**Comment by DragonBe** [comment]
@miclf even small contributions are contributions and your efforts to improve the tool are highly appreciated. No matter if it's code contribution or documentation improvements. So, yes… your opinion is just as valid.

As proof of your value are your comments you posted on the documentation for on-boarding and welcoming other contributors. Unfortunately I'm tied up until tonight to apply your valuable suggestions, would you be so kind to update the documentation with your suggestions? 

Not only have you committed a bit more, but you're point on in regards to the pre-knowledge of GIT and the confusion the text makes forking the repo.

**Comment by jkuchar** [comment]
This is a step forward, thanks to making it. I can agree with everything in those documents. 

@miclf GIT is nowadays very common. I would assume in document that people already knows the basics (terminology). To not make this requirement hard, you can link to GIT tutorials, such a [1](https://www.atlassian.com/git/tutorials) [2](https://try.github.io) [3](https://www.codecademy.com/learn/learn-git).

**Pull request merged**
