### PR TITLE
147 heartbeat not working anymore

### PR DESCRIPTION
**Pull request by 013cbr**
I've updated the heartbeat url, to make it look at the actual VIES-check endpoint. Unit tests are successful, but the build seems to fail on random stuff (php version, composer, etc).

### CODE REVIEW

**Comment by joseEkcit** [comment]
I humbly ask if this will be merged anytime soon.

**Comment by lruozzi9** [comment]
Hi @DragonBe! We are very grateful for your work on this package, but as you can see on issue #148 it is no more working. 
Can you have a look at this PR? Do you think it could be a nice solution? As I can see by the diff it introduces some breaking changes, if it is not possible to release a new major I can try to change it by not breaking the retro-compatibility.

**Comment by matthiasnoback** [comment]
Hi @DragonBe ! I'd also appreciate it if this issue could be fixed/merged.

**Comment by DrakkoFire** [comment]
I don't think this project is still being maintained, the last commit was 2 years ago...

**Comment by DragonBe** [comment]
My bad, I haven't given this project the necessary love it deserved. I'm back and ready to make some really necessary improvements.

**Pull request merged**
