### PR TITLE
Pre-validation of VAT numbers

### PR DESCRIPTION
**Pull request by krzaczek**
Hi,

This enables pre-validation of vat numbers before hitting API.
Had to modify test because vat number BE0123456789 is invalid (checksum is wrong)

Pawel

### CODE REVIEW

**Comment by krzaczek** [comment]
Looks like build faild becouse of github.com problems. Should pass after restarting.

**Comment by krzaczek** [comment]
Fixed some datetime issues. The date returned by api is not Y-m-d+H:i but the last part is (Difference to Greenwich time) so the propper format is Y-m-dP

see http://www.w3schools.com/schema/schema_dtypes_date.asp - Timezone part

**Comment by DragonBe** [comment]
Hey @krzaczek,

Sorry for the dealy, things were a bit hectic at my side. Anyways, I've reviewed your code and accepted your pull request.

Thank you for your contribution, I very much appreciate it.

**Comment by krzaczek** [comment]
@DragonBe Thx .. i'm still working on it ... need to fix some tests (dates) and will add one more method - set requester vat number ... to be able to get "Consultation Number" from the VIES api

**Pull request merged**
